# Generated by Django 2.2.7 on 2019-12-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
