# Generated by Django 2.2.5 on 2019-12-30 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('first_app', '0002_auto_20191226_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_object_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_content_type', to='contenttypes.ContentType')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sender', 'receiver_content_type', 'receiver_object_id')},
            },
        ),
    ]
