# Generated by Django 2.2.5 on 2019-12-30 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_like'),
    ]

    operations = [
    #    migrations.AddField(
    #        model_name='post',
    #        name='likes',
    #        field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
    #    ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
