# Generated by Django 2.2 on 2020-01-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_delete_userprofile'),
        ('first_app', '0005_post_slug'),
    ]

    operations = [
    ]
