# Generated by Django 2.2.5 on 2020-01-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_delete_userprofile'),
        ('first_app', '0005_post_slug'),
    ]

    operations = [
    ]
