# Generated by Django 2.2.5 on 2020-01-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200102_0040'),
        ('first_app', '0005_post_slug'),
    ]

    operations = [
    ]
