# Generated by Django 2.2.5 on 2020-01-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_account_is_sponsor'),
        ('first_app', '0006_merge_20200102_0056'),
        ('first_app', '0006_merge_20200107_1050'),
    ]

    operations = [
    ]
